# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4832186a3a7a193c5bd2a5529dfb2312127a9614e53ec563a728037513e10b19279a7d463ee254903585466e49e986933f897ce312258d04b13b6d213faa11ec

test:
  secret_key_base: 30c31115f0a95400b4278d6d7dd0faafb4383625ff14e59a7e93457b3b314427859dabbc9946816fe02803467b91cd6a7fb89a17ec6e73c3e72f21e84a107541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
